In [10]:
import numpy as np
a1=np.array([[1,2],[2,3],[4,5]],  dtype=np.float64)#by default it is int32
a2=np.array([[5,6],[7,8],[8,9]] ,dtype=np.float64)
print(a1+a2)

[[ 6.  8.]
 [ 9. 11.]
 [12. 14.]]


In [28]:
a=np.zeros(    (4,4)    )
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
a1[1]=[5,4]
a1

array([[1., 2.],
       [5., 4.],
       [4., 5.]])

In [77]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
a1.reshape((2,3))

array([[1., 2., 2.],
       [3., 4., 5.]])

In [64]:
a1.ravel()

array([1., 2., 2., 3., 4., 5.])

In [20]:
for i in a1.flatten():
    print(i)


1.0
2.0
5.0
4.0
4.0
5.0


In [66]:
a.min()

1

In [68]:
a.max()

9

In [21]:
ary=np.arange(10).reshape(2,5)
ary

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
ary.sum()
ary.sum(axis=0)


array([ 5,  7,  9, 11, 13])

In [88]:
ary.sum(axis=1)

array([10, 35])

In [90]:
np.sqrt(ary)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [92]:
np.std(ary)

2.8722813232690143

In [93]:
np.mean(ary)

4.5

In [94]:
ary*ary

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])